name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        npx redoc-cli build -t template.hbs iwine_openapi.yaml && \
        mv redoc-static.html index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.iwine_openapi.yaml,description.md,template.hbs,make.sh'